const actionTypes = {
    GET_HOME: 'GET_HOME',

    SET_FILTER_LIST: 'SET_FILTER_LIST',

    SET_PAGE: 'SET_PAGE',

    SET_CURRENT_SHOES_ID: 'SET_CURRENT_SHOES_ID',

    SET_CART_ITEM: 'SET_CART_ITEM',

    INCRE_ITEM_CART: 'INCRE_ITEM_CART',

    DECRE_ITEM_CART: 'DECRE_ITEM_CART',

    DELETE_ITEM_CART: 'DELETE_ITEM_CART',
};

export default actionTypes;
